import { addIcons } from 'ionicons';
import {
    menuOutline,
    sunnyOutline,
    moonOutline,
    logoGoogle,
    logOutOutline,
    appsOutline,
    rocketOutline,
    heartOutline,
    trophyOutline,
    arrowForwardOutline,
    homeOutline,
    informationCircleOutline,
    checkmarkCircleOutline,
    mailOutline,
    callOutline,
    locationOutline,
    closeOutline,
    personCircleOutline,
    trashOutline,
    mailOpenOutline,
    shieldCheckmarkOutline,
    warningOutline,
    calendarOutline,
    paperPlaneOutline
} from 'ionicons/icons';

export const registerIcons = () => {
    addIcons({
        menuOutline,
        sunnyOutline,
        moonOutline,
        logoGoogle,
        logOutOutline,
        appsOutline,
        rocketOutline,
        heartOutline,
        trophyOutline,
        arrowForwardOutline,
        homeOutline,
        informationCircleOutline,
        checkmarkCircleOutline,
        mailOutline,
        callOutline,
        locationOutline,
        closeOutline,
        personCircleOutline,
        trashOutline,
        mailOpenOutline,
        shieldCheckmarkOutline,
        warningOutline,
        calendarOutline,
        paperPlaneOutline
    });
};
